add SINGLE_SEARCH_MODE for rgf - toggle between rg & fzf, not AND continue to improve pipe input, still having issue

diff --git a/rgf b/rgf
--- a/rgf
+++ b/rgf
@@ -9,6 +9,10 @@
 # usage:
 # rgf [file] [regex]
 
+# known issue:
+# when pipeline input contains bash escape sequence, echo will attempt to interpret it and cause undesired string evaluation
+# e.g., '\\\$\(CMD\)', this sequence will consistently break the program
+
 if [[ "$1" == "-h" || "$1" == "--help" ]]; then
     echo "usage: rgf [file] [regex]  # both params are optional"
     echo "reading from pipe is supported though not recommanded for large input"
@@ -18,7 +22,21 @@ if [[ "$1" == "-h" || "$1" == "--help" ]]; then
     exit 0
 fi
 
-RG_PREFIX="rg --column --line-number --no-heading --color=always --smart-case"
+RG_PREFIX="rg --line-number --no-heading --color=always --smart-case"
+NOT_FOUND_PROMPT="echo '[[ regex:/{q}/ not found ]]'"
+PRETTY_BAT='bat --color=always --terminal-width $(tput cols)'
+ECHO="printf"
+PATTERN_SETUP="PATTERN=\$([ -z '{q}' ] && echo '' || echo '-p {q}')"
+
+# Only one engine is used during search, ctrl-t only changes the search engine
+SINGLE_SEARCH_MODE="ctrl-t:transform:[[ ! \$FZF_PROMPT =~ rg ]] &&
+                    echo \"rebind(change)+reload($RG_PREFIX {q} || $NOT_FOUND_PROMPT)+change-prompt(1. rg> )+disable-search\" ||
+                    echo \"unbind(change)+reload($RG_PREFIX '')+change-prompt(2. fzf> )+enable-search\" "
+
+# Both engines are used, you can perform rg "foo" && fzf "bar" - there is an logical AND opertion implied
+DUAL_SEARCH_MODE='ctrl-t:transform:[[ ! $FZF_PROMPT =~ rg ]] &&
+                  echo "rebind(change)+change-prompt(1. rg> )+disable-search+transform-query:echo \{q} > /tmp/rg-fzf-f; cat /tmp/rg-fzf-r" ||
+                  echo "unbind(change)+change-prompt(2. fzf> )+enable-search+transform-query:echo \{q} > /tmp/rg-fzf-r; cat /tmp/rg-fzf-f"'
 
 if ! [ -p /dev/stdin ]; then
 
@@ -29,50 +47,43 @@ if ! [ -p /dev/stdin ]; then
     rm -f /tmp/rg-fzf-{r,f}
     INITIAL_QUERY="${*:-}"
     : | fzf --ansi --disabled --query "$INITIAL_QUERY" \
-        --layout=reverse \
+        --layout=reverse-list \
         --exact \
-        --bind "start:reload:$RG_PREFIX {q} $file_path" \
-        --bind "change:reload:sleep 0.1; $RG_PREFIX {q} $file_path || true" \
-        --bind 'ctrl-t:transform:[[ ! $FZF_PROMPT =~ rg ]] &&
-            echo "rebind(change)+change-prompt(1. rg> )+disable-search+transform-query:echo \{q} > /tmp/rg-fzf-f; cat /tmp/rg-fzf-r" ||
-            echo "unbind(change)+change-prompt(2. fzf> )+enable-search+transform-query:echo \{q} > /tmp/rg-fzf-r; cat /tmp/rg-fzf-f"' \
+        --bind "start:reload:$RG_PREFIX {q} $file_path || $NOT_FOUND_PROMPT" \
+        --bind "change:reload:sleep 0.1; $RG_PREFIX {q} $file_path || $NOT_FOUND_PROMPT" \
+        --bind "$SINGLE_SEARCH_MODE"\
         --color "hl:-1:underline,hl+:-1:underline:reverse" \
         --prompt "1. rg>" \
         --delimiter : \
         --header 'CTRL-T: Switch between rg/fzf' \
-        --preview 'bat --terminal-width $FZF_PREVIEW_COLUMNS --color=always {1} --highlight-line {2}' \
+        --preview 'bat --terminal-width $FZF_PREVIEW_COLUMNS --color=always {1} --highlight-line {2} 2>/dev/null || echo [empty]' \
         --preview-window 'up,60%,border-bottom,+{2}+3/3,~3' \
-        --bind 'enter:become(vim {1} +{2})' \
+        --bind "enter:execute( $PATTERN_SETUP ; $PRETTY_BAT {1} | less -R +{2} \$PATTERN ; echo '{1}:{2}')" \
         --bind 'ctrl-/:change-preview-window(right|up|hidden|)'
 
 else
 
     # Run from pipeline
 
-    PIPE_IN=()
-    while IFS= read -r line; do
-        PIPE_IN+=("$line")
-    done
-
-    joined_string=$(printf "%s\n" "${PIPE_IN[@]}")
+    joined_string=$(cat | sed -e "s+\\$+\\\\$+g") # escape $
 
     rm -f /tmp/rg-fzf-{r,f}
     INITIAL_QUERY="${*:-}"
-    echo -e "$joined_string" | fzf --ansi --disabled --query "$INITIAL_QUERY" \
-        --layout=reverse \
+    $ECHO "$joined_string" | fzf --ansi --disabled --query "$INITIAL_QUERY" \
+        --layout=reverse-list \
         --exact \
-        --bind "start:reload:echo -e '$joined_string' | $RG_PREFIX {q}" \
-        --bind "change:reload:sleep 0.1;echo -e '$joined_string' | $RG_PREFIX {q} || true" \
-        --bind 'ctrl-t:transform:[[ ! $FZF_PROMPT =~ rg ]] &&
-            echo "rebind(change)+change-prompt(1. rg> )+disable-search+transform-query:echo \{q} > /tmp/rg-fzf-f; cat /tmp/rg-fzf-r" ||
-            echo "unbind(change)+change-prompt(2. fzf> )+enable-search+transform-query:echo \{q} > /tmp/rg-fzf-r; cat /tmp/rg-fzf-f"' \
+        --bind "start:reload:$ECHO \"$joined_string\" | $RG_PREFIX {q} || $NOT_FOUND_PROMPT" \
+        --bind "change:reload:sleep 0.1;$ECHO \"$joined_string\" | $RG_PREFIX {q} || $NOT_FOUND_PROMPT" \
+        --bind "ctrl-t:transform:[[ ! \$FZF_PROMPT =~ rg ]] &&
+                  echo 'rebind(change)+reload($ECHO \"$joined_string\" | $RG_PREFIX {q} || $NOT_FOUND_PROMPT)+change-prompt(1. rg> )+disable-search' ||
+                  echo 'unbind(change)+reload($ECHO \"$joined_string\" | $RG_PREFIX \"\" )+change-prompt(2. fzf> )+enable-search' "\
         --color "hl:-1:underline,hl+:-1:underline:reverse" \
         --prompt "1. rg>" \
         --delimiter : \
         --header 'CTRL-T: Switch between rg/fzf' \
-        --preview "echo -e '$joined_string' | bat --terminal-width \$FZF_PREVIEW_COLUMNS --color=always --highlight-line {1}" \
+        --preview "$ECHO \"$joined_string\" | bat --terminal-width \$FZF_PREVIEW_COLUMNS --color=always --highlight-line {1} || echo [empty]" \
         --preview-window 'up,60%,border-bottom,+{1}/3' \
-        --bind "enter:become( PATTERN=\$([ -Z '{q}' ] && echo '' || echo '-p {q}') ; echo -e '$joined_string' | bat --color=always --terminal-width $(tput cols) | less -R \$PATTERN )" \
+        --bind "enter:execute( $PATTERN_SETUP ; $ECHO \"$joined_string\" | $PRETTY_BAT | less -R +{1} \$PATTERN )" \
         --bind 'ctrl-/:change-preview-window(right|up|hidden|)'
 
 fi
